/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [QLNS]    Script Date: 5/17/2018 7:31:38 PM ******/
CREATE DATABASE [QLNS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLNS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\QLNS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLNS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\QLNS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [QLNS] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLNS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLNS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLNS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLNS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLNS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLNS] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLNS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLNS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLNS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLNS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLNS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLNS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLNS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLNS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLNS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLNS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QLNS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLNS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLNS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLNS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLNS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLNS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLNS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLNS] SET RECOVERY FULL 
GO

ALTER DATABASE [QLNS] SET  MULTI_USER 
GO

ALTER DATABASE [QLNS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLNS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLNS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLNS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLNS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLNS] SET QUERY_STORE = OFF
GO

USE [QLNS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [QLNS] SET  READ_WRITE 
GO

